### ISSUE TITLE
Problem installing reduce on Mac

### ISSUE THREAD

**Issue by pschicho** [tueda/homebrew-loops#4]
Hi,

I am trying to install reduze with your hombrew tap. My operating system is maxOS Sierra 10.12.6. Eventually I get this error which I can not make much out of. Especially as I have installed the correct version of GiNaC

```
/usr/local/include/ginac/ex.h:119:30: error: member reference type 'ptr<GiNaC::basic>' is not a pointer; did you mean to use '.'?
        ex evalf() const { return bp->evalf(); }
                                  ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [reduze/CMakeFiles/reduze.dir/crossing.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
20 errors generated.
make[2]: *** [reduze/CMakeFiles/reduze.dir/combinatorics.cpp.o] Error 1
20 errors generated.
make[2]: *** [reduze/CMakeFiles/reduze.dir/color.cpp.o] Error 1
20 errors generated.
make[2]: *** [reduze/CMakeFiles/reduze.dir/amplitude.cpp.o] Error 1
make[1]: *** [reduze/CMakeFiles/reduze.dir/all] Error 2
make: *** [all] Error 2
```

Thanks for your help.
Cheers Philipp

**Comment by tueda** [comment]
Thanks for the report. I got similar compilation errors for reduze 2.1 with ginac 1.7.2 on Linux (using linuxbrewed gcc 5.3.0). I guess the problem is that ginac has moved to C++11.

I have almost no experience with macOS/Homebrew, but maybe your C++ compiler (you can see it in the Homebrew's error log) could be in the classical C++98 mode by default without any command line options? Maybe installing `gcc` by Homebrew would resolve the issue for you (if it's possible), because g++ 6 and 7 are shipped `-std=gnu++14` by default.

I will consider patching `CMakeLists.txt` of reduze, which should be 1 or 2 lines, I hope...

**Comment by pschicho** [comment]
I have considered that because when installing reduze the "conventional" way I get multiple errors regarding probably my compiler. I have installed g++-7 via homebrew and tried to link in on command line which gave similar error in the compilation. I have attached the files of both running make -j 2 and make during the installation. 

[cmake.txt](https://github.com/tueda/homebrew-loops/files/1285464/cmake.txt)
[make.txt](https://github.com/tueda/homebrew-loops/files/1285465/make.txt)

**Comment by tueda** [comment]
I see. The download link from https://reduze.hepforge.org/ is now for `reduze-2.1-2-g8e3ef1d` instead of `reduze-2.1`, and the new version checks if c++11 is required, but still the compilation fails. It's a tough problem...

**Comment by tueda** [comment]
The updated formula uses a keg-only ginac 1.6.7 and must be successfully compiled.

**Comment by pschicho** [comment]
Thank you so much - it works perfectly now. That was a big help!!

**Comment by tueda** [comment]
Good to hear that it works also on your system.
